services:
  php:
    build:
      context: ./docker/php
    volumes:
      - .:/var/www/code
    working_dir: /var/www/code
    user: "1000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-app_user}:${POSTGRES_PASSWORD:-!ChangeMe!}@postgres:5432/${POSTGRES_DB:-app}?serverVersion=${POSTGRES_VERSION:-15}&charset=${POSTGRES_CHARSET:-utf8}
    depends_on:
      postgres:
        condition: service_started

  nginx:
    image: nginx
    ports:
      - "127.0.0.1:8001:80"
    volumes:
      - .:/var/www/code
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    depends_on:
      - php

  postgres:
    image: postgres:${POSTGRES_VERSION:-15}-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-app_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-ChangeMe}
      POSTGRES_DB: ${POSTGRES_DB:-app}
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw

volumes:
  postgres_data:
